### ISSUE TITLE
Available OSX environments

### ISSUE THREAD

**Issue by Flamefire** [CPPAlliance/drone-ci#13]
The documentation states

> For OSX builds, specify the xcode version instead of the image. Recent versions of xcode from 6.4 to 14.1 are available. Include xcode_version in the job definition in .drone.star, such as xcode_version="10.3".

However the `osx_cxx` function has `arch="amd64", osx_version=None, xcode_version=None,`

Which of those is actually usable and what are the potential versions?

I'm asking for the simplification in the branch https://github.com/boostorg/boost-ci/tree/drone-refactor where I currently support  `osx-<version>`,  `osx-xcode-<version>` and  `osx-<version>-xcode-<version>` formats but I want to check what actually makes sense. I.e. it looks like only the 2nd variant makes sense.

So which OSX images are there and what xcode versions do they have?

Asking also due to a failure with XCode 9.4.1 where the compiler seems to have `nullptr` but the std libary is lacking `std::nullptr_t` and it shows a deprecation warning (see https://drone.cpp.al/boostorg/boost-ci/333/33/2)

**Comment by sdarwin** [comment]
In drone-ci.md for OSX it says "List of available versions" 

> Which of those is actually usable?

Those are the actual available hosted versions of Xcode.

Choosing the Xcode version is the preferred way of ending up with an operating system. `functions.star` will determine the OS.

```
  if xcode_version:
    job_env["DEVELOPER_DIR"] = "/Applications/Xcode-" + xcode_version +  ".app/Contents/Developer"
    if not osx_version:
        if xcode_version[0:2] in [ "14", "13"]:
            osx_version="monterey"
        elif xcode_version[0:4] in [ "12.5"]:
            osx_version="monterey"
        elif xcode_version[0:2] in [ "12","11","10"]:
            osx_version="catalina"
        elif xcode_version[0:1] in [ "9","8","7","6"]:
            osx_version="highsierra"
  elif not osx_version:
    osx_version="catalina"
```

It should be possible, and functional, to choose just the OS version instead by setting osx_version and ignore Xcode.   If you run a test that doesn't use Xcode and only selects the OS.

It is not possible to set both xcode_version and osx_version to arbitrary values. Use one or the other, but not both.

Now that functions.star has `unix_common`, it's slightly awkward to place apple-specific diagnostics into `unix_common`. So, we could put the command

`sw_vers`

in https://github.com/boostorg/boost-ci/blob/master/ci/drone/osx-cxx-install.sh .

Notice that xcode 13 and 14 are running on "monterey". Those machines have been updated to be M1 arm processors.  Drone seems to be ignoring the `arch=` setting since the builds are working with the wrong arch.

**Comment by Flamefire** [comment]
Thanks!
