### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by jzmaddock** [CPPAlliance/drone-ci#5]
I've added a drone config to Boost.Math, it's mostly working well, but it seems to be running twice: https://github.com/boostorg/math/pull/508

The first run of these has everything fail when checking out boost:

```

+ git clone -b drone --depth 1 https://github.com/boostorg/boost.git boost-root
--
Cloning into 'boost-root'...
warning: Could not find remote branch drone to clone.
fatal: Remote branch drone not found in upstream origin
```

In other words it's using the branch name of the Math lib for checking out Boost which is doomed to fail.

The second of the 2 runs works as expected.

Have I goofed in the setup somewhere?

Many thanks!

**Comment by sdarwin** [comment]
Hi @jzmaddock ,

The same thing would presumably occur with travis.

```
git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
```

"""
TRAVIS_BRANCH:
for push builds, or builds not triggered by a pull request, this is the name of the branch.
for builds triggered by a pull request this is the name of the branch targeted by the pull request.
"""

The first build, based on a push to the "drone" branch, would fail.
The second build, based on a pull request, would see the branch targeted by the pull request, and succeed.

Many solutions:
- submit pull requests from a forked repository instead of from the same one.   That's typically what happens.
- or, hardcode $TRAVIS_BRANCH to "develop" in the drone files. 
- or, do something like what boost-ci/ci/common-install.sh does
```
# Handle also /refs/head/master
if [ "$BOOST_CI_TARGET_BRANCH" == "master" ] || [[ "$BOOST_CI_TARGET_BRANCH" == */master ]]; then
    export BOOST_BRANCH="master"
else
    export BOOST_BRANCH="develop"
fi
```
- or, leverage boost-ci/ci/common-install.sh, an example CI script for that: https://github.com/boostorg/boost-ci/blob/master/.travis.yml

**Comment by jzmaddock** [comment]
Thanks Sam, I'll look at the branch checkout issue later, in the mean time I'll just note that the "double build" issue doesn't show up in multiprecision, see for example https://github.com/boostorg/multiprecision/pull/288 even though it's exactly the same situation with regard to branches (all the drone setup files were copied over from there as well).

On a related note, I've just killed this Boost.Math drone run which apparently still had jobs running after 6+ hours: https://drone.cpp.al/boostorg/math/8/141/2.  I do note that some of these tests chew up a fair bit of memory, so I suspect they're basically just thrashing the swap file until everything grinds to a halt.  I'm trying to reduce the memory footprint now, but it's hard going.  Any thoughts?

Thanks again, John.

**Comment by sdarwin** [comment]
> the "double build" issue

Just realized, there's another explanation: https://github.com/boostorg/boost-ci/blob/master/ci/drone/functions.star
```
"trigger": { "branch": [ "master","develop", "drone*", "bugfix/*", "feature/*", "fix/*", "pr/*" ] },
```
Triggers on certain branches, including the "drone" branch. But not _all_ branches. So, a typical push to a new branch will usually not cause a build.   I added "drone" to this list because if someone were testing drone in particular, they might call the branch "dronetest1" , and expect it to build in drone.   

The boost branch should probably not exactly be linked to the TRAVIS_BRANCH.   Boost should only use "develop" or "master".

>  jobs running after 6+ hours:

The agent instances might have depleted memory, and become unreachable.   
The autoscaler is launching m5.large instances 8.0 GiB | 2 vCPUs
My first thought was to upgrade to a large instance type. But instead, how about changing DRONE_AGENT_CONCURRENCY from 2 to 1.   
When the next batch of agents launch, maybe in a couple of hours, each job will have a dedicated 8GB of memory, instead of sharing that between 2 jobs.

**Comment by sdarwin** [comment]
Some jobs are still running out of memory. This morning, I have added DRONE_LIMIT_MEM=6000000000 to the server, limiting memory to 6GB. This should prevent the agent process from crashing.   In the future, if more jobs are packed onto a single server, I wonder if a smaller number such as 3GB per job would be sufficient..

**Comment by jzmaddock** [comment]
Thanks for your help Sam, the remaining Math lib issues I can sort out from here I hope.

On an unrelated note: I'm currently chasing down an XCode-12 Boost.Config issue, any chance of adding support for that?  I can add it to GHA for the moment so there's no rush or anything.

**Comment by sdarwin** [comment]
Xcode 12.1, 12.2, 12.3 added.

**Comment by jzmaddock** [comment]
That's great - thanks Sam!
