### ISSUE TITLE
ASAN for unordered

### ISSUE THREAD

**Issue by Flamefire** [CPPAlliance/drone-ci#9]
Can I get trusted for https://github.com/boostorg/unordered and my fork https://github.com/Flamefire/unordered please?

**Comment by sdarwin** [comment]
Please get drone up and running first, then I will have access to the settings for those repositories.

Certainly it would be preferable if ASAN could just work automatically.   

But it seems that it requires docker to be "trusted".   and that is a setting.

**Comment by Flamefire** [comment]
For my fork Drone already ran, but failed the ASAN job of course. For boostorg there is an open PR: https://github.com/boostorg/unordered/pull/124

**Comment by sdarwin** [comment]
Oh, drone's URLs are case sensitive.  

Flamefire/ has been updated.

For boostorg/unordered, a repository admin needs to log into drone, "sync repos", and add boostorg/unordered.

**Comment by sdarwin** [comment]
Regarding boostorg/unordered Peter wrote:

`
drone.cpp.al has limited capacity and I don't think we should be carpet bombing it with jobs we don't actually need because they are already covered elsewhere. This will ruin it for everyone.
`

This is partially true, but not completely.  
Linux tests, both arm64 and x86_64, are autoscaled and not limited.   
Windows, Mac, and s390x are constrained by the fact they run on single instances or physical servers. 
If Drone will improve their autoscaler, which is actually possible,  Windows and s390x instances could also be included. That would only leave out Mac OSX.   
After a set of servers is autoscaled, it makes more sense to add in the boost-ci config and allow carpet bombing.
